<a href="https://colab.research.google.com/github/rishikachowdaryg/American-Express-Data-Analysis/blob/main/American_Express_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0'

In [5]:
dataset = pd.read_csv('American Express User Exit Pred.csv')
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


In [7]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
X[:, 2] = label_encoder.fit_transform(X[:, 2])

In [8]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
ann = tf.keras.models.Sequential()

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 120)

Epoch 1/120
249/249 [==============================] - 1s 1ms/step - loss: 0.5130 - accuracy: 0.7912
Epoch 2/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4621 - accuracy: 0.7966
Epoch 3/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4485 - accuracy: 0.7966
Epoch 4/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4407 - accuracy: 0.7966
Epoch 5/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4357 - accuracy: 0.7966
Epoch 6/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4329 - accuracy: 0.7966
Epoch 7/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4310 - accuracy: 0.7966
Epoch 8/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4295 - accuracy: 0.7981
Epoch 9/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4284 - accuracy: 0.8044
Epoch 10/120
249/249 [==============================] - 0s 1ms/step - loss: 0.4272 - accura

In [19]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]])) > 0.5)

[[False]]


In [20]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [1 1]]


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1471  102]
 [ 233  180]]


0.8313192346424975